apiVersion: certificates.k8s.io/v1beta1
kind: CertificateSigningRequest
metadata:
  name: webhook.webhook
spec:
  request: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQkxEQ0Iwd0lCQURBc01Tb3dLQVlEVlFRREV5RjNaV0pvYjI5ckxuZGxZbWh2YjJzdWMzWmpMbU5zZFhOMApaWEl1Ykc5allXd3dXVEFUQmdjcWhrak9QUUlCQmdncWhrak9QUU1CQndOQ0FBU2F3aUhJUFhiUmhnd0NXZUt2Ckp4YnBNdEhBZUJjWHo5V2wwaC9IUlR1WWlicFJMRmk2TkZRY3VCZVRhU2hzOTN3NTFMamdYVFBBd1ZLRlNXU2sKZ05wc29FVXdRd1lKS29aSWh2Y05BUWtPTVRZd05EQXlCZ05WSFJFRUt6QXBnaUYzWldKb2IyOXJMbmRsWW1odgpiMnN1YzNaakxtTnNkWE4wWlhJdWJHOWpZV3lIQkFxWXQxc3dDZ1lJS29aSXpqMEVBd0lEU0FBd1JRSWdSTkg0ClEzU3ZvWGNRbFZpc3hneHlGT2N0Q2xSVVZHL241VnBDVElVR1NUY0NJUURPcXdhcWVQWkdzbE9WY0hNQmxkS2cKUHNRUTdoVWRrME1zK1BFazlYS1o5QT09Ci0tLS0tRU5EIENFUlRJRklDQVRFIFJFUVVFU1QtLS0tLQo=
  usages:
  - digital signature
  - key encipherment
  - server auth