# apiVersion: v1
# kind: Namespace
# metadata:
#   name: webhook
# ---
apiVersion: v1
kind: Service
metadata:
  name: webhooktest
  namespace: webhook
  labels:
    kubernetes.io/name: "webhooktest"
    # kubernetes.io/cluster-service: "true" 
spec:
  selector:
    k8s-app: webhooktest
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080