# apiVersion: v1
# kind: Namespace
# metadata:
#   name: webhook
# ---
apiVersion: v1
kind: Service
metadata:
  name: webhook
  namespace: webhook
  labels:
    app: webhook
spec:
  selector:
    app: webhook
  ports:
  - port: 443
    protocol: TCP
    targetPort: 8080
    nodePort: 31111
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webhook
  namespace: webhook
  labels:
    app: webhook
spec:
  selector:
    matchLabels:
      app: webhook
  template:
    metadata:
      labels:
        app: webhook
    spec:
      containers:
      - name: webhook
        image: localhost:32000/webhook
        ports:
        - containerPort: 8080
          name: normal
        volumeMounts:
        - name: certs
          mountPath: /certswebhook
      volumes:
      - name: certs
        secret:
          secretName: webhook-server-tls