# apiVersion: v1
# kind: Namespace
# metadata:
#   name: webhooktest
---
apiVersion: v1
kind: Service
metadata:
  name: webhooktest
  namespace: webhook
  labels:
    kubernetes.io/name: "webhooktest"
    # kubernetes.io/cluster-service: "true" 
spec:
  selector:
    app: webhooktest
  ports:
  - port: 8080
    name: https
    protocol: TCP
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webhooktest
  namespace: webhook
  labels:
    app: webhooktest
spec:
  selector:
    matchLabels:
      app: webhooktest
  template:
    metadata:
      labels:
        app: webhooktest
    spec:
      containers:
      - name: webhooktest
        image: localhost:32000/webhooktest
        ports:
        - containerPort: 8080
          name: normal